### PR TITLE
Support TSX

### PR DESCRIPTION
**Pull request by hm-lee**
### Added the following Features:
- It already support JSX, but i added another option to support TSX. 😊

### CODE REVIEW

**Comment by mvdschee** [comment]
He @hm-lee you're right let's not forget the Typescript version 😄

**Comment by mvdschee** [comment]
If you could add one more change for me in `/client/src/extension.ts` around rule 35 `{ language: 'typescriptreact', scheme: 'file' },` I can accept your pull :)

**Comment by hm-lee** [comment]
OK! I'll be update it! 👀

**Comment by hm-lee** [comment]
@mvdschee fixed! 👀

**Comment by hm-lee** [comment]
@mvdschee hi! is there any update plan exist of the vscode marketplace?
I want to share this extensions with the my company team.😊

**Comment by mvdschee** [comment]
He @hm-lee I will do a hotfix for this one, I haven't fixed enough issues to set up an other full on release, so expect it in like a couple hours.

**Comment by mvdschee** [comment]
He @hm-lee you I was checking and it doesn't seem to hit on the `` for my small test. So you got any project with TypeScript React for me that I can use to test and debug?

**Comment by hm-lee** [comment]
@mvdschee 
Oh, I saw it late, my projects are company products... 🤔
so how about the example of the project below?
I'll keep looking for better examples.
https://github.com/dl0312/react-typescript-boilerplate

**Comment by mvdschee** [comment]
Hmm I need like a good representation of how a React developer would write it's HTML (obviously that's a per person difference) but I don't use react for that. I can just add it but there's a big change that i wont trigger on any A11y rules, just don't want to give people a false hope of writing accessible code.

**Pull request merged**
